version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8080:8080"