openapi: 3.0.3
info:
  title: Sensor Data Flask API
  contact:
    email: edwinkassier@gmail.com
  version: 1.0.0
  
servers:
  - url: http://127.0.0.1:8080/api/v1/core
    description: e.g. Internal server for testing
    
paths:
  /process_request:
    get:
      summary: Process a request for input
      description: Get the results of a request for the given sensor data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Bad request. There was an issue with the structure of the querys
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bad_Response'
                
components:
  schemas:
    Response:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ResponseItem'
        graph_data:
          type: array
          items:
            $ref: '#/components/schemas/GraphItem'
      required:
        - message
        - graph_data
        
    Bad_Response:
      type: object
      properties:
        message:
          type: string
          example: 'Server Failure'
      required:
        - message
        
    ResponseItem:
      type: string
      properties:
        message:
          type: string
          example: "Data available"
        
          
    GraphItem:
      type: object
      properties:
        device_id:
          type: string
          example: device.foo
        parameter:
          type: string
          example: parameter.foo
        timestamp:
          type: string
          format: date-time
          example: "2024-03-07T12:22:07.315194"
        value:
          oneOf:
            - type: string
            - type: number
          example: "401.892566143913"
