# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"0\n\napiRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x12\n\ninvestment\x18\x02 \x01(\x05\"2\n\x0b\x61piResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\ngraph_data\x18\x02 \x01(\t24\n\x03\x41PI\x12-\n\x0eprocessRequest\x12\x0b.apiRequest\x1a\x0c.apiResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APIREQUEST']._serialized_start=13
  _globals['_APIREQUEST']._serialized_end=61
  _globals['_APIRESPONSE']._serialized_start=63
  _globals['_APIRESPONSE']._serialized_end=113
  _globals['_API']._serialized_start=115
  _globals['_API']._serialized_end=167
# @@protoc_insertion_point(module_scope)
